name: lint

on:
  push:
    branches:
      - 2.x
      - 1.x
      - main

permissions:
  contents: write

jobs:
  lint:
    uses: Solar-Investments/.github/.github/workflows/lint.yml@main
    secrets: inherit
